version: "3.9"

services:
#  front:
#    image: sermalenk/skypro-front:lesson-35
#    restart: always
#    ports:
#      - "80:80"
#      - "8000:8000"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#    depends_on:
#      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
    restart: always
    ports:
      - "5432:5432"


volumes:
  postgres_data: