# Generated by Django 4.0.1 on 2022-12-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.CharField(max_length=255, verbose_name='id чата'),
        ),
    ]
